const TOOGLE_MODAL = 'TOOGLE_MODAL'
const MODAL_UPDATE_TYPE = 'MODAL_UPDATE_TYPE'
const MODAL_URL = 'MODAL_URL'
const CLOSE_MODAL = 'CLOSE_MODAL'

export { TOOGLE_MODAL, MODAL_UPDATE_TYPE, MODAL_URL, CLOSE_MODAL }
